name: Build Binaries for KHA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Navigate to kha-e directory
        run: cd kha-e

      - name: Install Dependencies
        run: npm install
        working-directory: kha-e  # Este parámetro asegura que npm install se ejecute en kha-e

      - name: Build Windows Executable
        run: npm run build:windows
        working-directory: kha-e  # Asegura que npm run build:windows se ejecute en kha-e

      - name: Build macOS Executable
        run: npm run build:mac
        working-directory: kha-e  # Asegura que npm run build:mac se ejecute en kha-e

      - name: Build Linux Executable
        run: npm run build:linux
        working-directory: kha-e  # Asegura que npm run build:linux se ejecute en kha-e

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: kha-e/dist  # Ajusta esto según donde exactamente se generan los ejecutables en kha-e
