name: Build and Release KHA

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: kha-e  

      - name: Debug files in directory
        run: ls -R
        working-directory: kha-e

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        working-directory: kha-e  

      - name: Build for Windows
        run: npm run build:windows
        working-directory: kha-e

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v2
        with:
          name: electron-windows
          path: kha-e/dist/win

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: kha-e

      - name: Debug files in directory
        run: ls -R
        working-directory: kha-e

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        working-directory: kha-e

      - name: Build for macOS
        run: npm run build:mac
        working-directory: kha-e

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v2
        with:
          name: electron-mac
          path: kha-e/dist/mac

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: kha-e

      - name: Debug files in directory
        run: ls -R
        working-directory: kha-e

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        working-directory: kha-e

      - name: Build for Linux
        run: npm run build:linux
        working-directory: kha-e

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v2
        with:
          name: electron-linux
          path: kha-e/dist/linux

  release:
    needs: [build-windows, build-mac, build-linux]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: kha-e

      - name: Download Windows artifacts
        uses: actions/download-artifact@v2
        with:
          name: electron-windows
          path: kha-e/dist/win

      - name: Download macOS artifacts
        uses: actions/download-artifact@v2
        with:
          name: electron-mac
          path: kha-e/dist/mac

      - name: Download Linux artifacts
        uses: actions/download-artifact@v2
        with:
          name: electron-linux
          path: kha-e/dist/linux

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kha-e/dist/win/*
            kha-e/dist/mac/*
            kha-e/dist/linux/*
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
